using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Schema;
using Newtonsoft.Json.Schema.Generation;
namespace intersecting_rectangles
{
    public class RectanglesDTO
    {
        [JsonProperty("rects", Required = Required.Always)]
        public List<RectangleDTO> rects;
        
        
        public static JSchema getJsonSchema()
        {
            /* manually generated by hand */
            /* 
            return JSchema.Parse(@"{
                'type': 'object',
                'properties': {
                    'rects': {'type': 'array', 
                        'items': {
                            'type': 'object',
                            'properties': {
                                'x': {'type': 'integer'},
                                'y': {'type': 'integer'},
                                'delta_x': {'type': 'integer'},
                                'delta_z': {'type': 'integer'},
                            },
                            'required': ['x','y','delta_x','delta_y']
                        }
                    }
                },
                'required': ['rects']
                }");
            */
            JSchemaGenerator generator = new JSchemaGenerator();
            JSchema schema = generator.Generate(typeof(RectanglesDTO));
            return schema;
        }
    }
}